export const filterData = [
                    {name:"돈까스.회.일식",image: require('../assets/pork.png'), id:"0"},
                    {name:"중식",image:require("../assets/Chinese.png"),id:"1"},
                    {name:"치킨",image:require("../assets/chicken.png"),id:"2"},
                    {name:"백반.죽.국수",image:require("../assets/noodle.png"),id:"3"},
                    {name:"카페.디저트",image:require("../assets/dessert.png"),id:"4"},
                    {name:"분식",image: require('../assets/tteokbokki.png'), id:"5"},
                    {name:"찜.탕.찌개",image:require("../assets/steamed.png"),id:"6"},
                    {name:"피자",image:require("../assets/Pizza.png"),id:"7"},
                    {name:"양식",image:require("../assets/western.png"),id:"8"},
                    {name:"고기.구이",image:require("../assets/meat.png"),id:"9"},
                    {name:"족발.보쌈",image: require('../assets/Bossam.png'), id:"10"},
                    {name:"아시안",image:require("../assets/asian.png"),id:"11"},
                    {name:"패스트푸드",image:require("../assets/fast.png"),id:"12"},
                    {name:"야식",image:require("../assets/night.png"),id:"13"},
                    {name:"도시락",image:require("../assets/lunchBox.png"),id:"14"},
                ];
